# Generated by Django 4.2.10 on 2024-03-06 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='admin',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('pw', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'admin',
                'managed': True,
            },
        ),
    ]
