# Generated by Django 4.2.10 on 2024-03-07 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0002_admin"),
    ]

    operations = [
        migrations.DeleteModel(name="user",),
    ]
