# Generated by Django 4.2.10 on 2024-03-02 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app02', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoneImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_h', models.PositiveIntegerField(default=200)),
                ('image_w', models.PositiveIntegerField(default=200)),
                ('done_time', models.TimeField(auto_now_add=True)),
                ('image_done', models.ImageField(height_field=models.PositiveIntegerField(default=200), upload_to='img_done/', width_field=models.PositiveIntegerField(default=200))),
            ],
        ),
        migrations.CreateModel(
            name='UploadImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_h', models.PositiveIntegerField(default=200)),
                ('image_w', models.PositiveIntegerField(default=200)),
                ('img_path', models.ImageField(height_field=models.PositiveIntegerField(default=200), upload_to='user_photo/', width_field=models.PositiveIntegerField(default=200))),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('u_id', models.AutoField(primary_key=True, serialize=False)),
                ('u_name', models.CharField(max_length=18, unique=True)),
                ('u_icon', models.ImageField(upload_to='user_icon/')),
                ('u_password', models.CharField(max_length=254)),
                ('u_sign', models.TextField()),
                ('u_email', models.EmailField(max_length=254)),
                ('u_ticket', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.AddField(
            model_name='uploadimage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app02.user'),
        ),
        migrations.AddField(
            model_name='doneimage',
            name='upload_image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app02.uploadimage'),
        ),
    ]
