# Generated by Django 4.2.10 on 2024-03-06 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app02', '0002_doneimage_uploadimage_user_delete_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadimage',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='u_email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='u_icon',
        ),
        migrations.RemoveField(
            model_name='user',
            name='u_password',
        ),
        migrations.RemoveField(
            model_name='user',
            name='u_sign',
        ),
        migrations.RemoveField(
            model_name='user',
            name='u_ticket',
        ),
    ]
